server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  application:
    name: Digital Health Passport
  http:
  datasource:
      url: jdbc:mysql://localhost:3306/dhp
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Park-sang1
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          batch_size:  10
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

